### ISSUE TITLE
As waifus não estão sendo exibidas

### ISSUE THREAD

**Issue by Kurumi30** [bruno-sartori/weeb-logger#3]
Salve Bruno!
A mensagem do log aparece, mas a imagem não
![image](https://github.com/user-attachments/assets/ee325cda-86e2-4e3c-9dcd-b6e2e89f470b)

- Criei um projeto Vite + TS
- Removi o arquivo style.css e no arquivo index.html apaguei a  ```<div id="app"></div>```
- Fiz a instalação usando ```pnpm add @bsartori/weeb-logger``` (testei com o npm também e não mudou nada)
- O código TS:
```typescript
import logger from "@bsartori/weeb-logger"

logger.configure({
  enabled: true,
  visual: true,
  containerStyle: {
    position: "bottom-right",
    height: 100,
    width: 100,
  },
  waifu: {
    useTheme: true,
    showWaifu: true,
    name: "masha",
  },
})

logger.highlight("Hello World", "Masha is cute!")
```

Imagem da aba Network:
![network](https://github.com/user-attachments/assets/f1390771-2ced-4952-bca2-c363ace6c9fd)

**Comment by bruno-sartori** [comment]
Eai @Kurumi30  tudo bem? Estou dando uma lida aqui e isso parece ser um bug aberto do Vite em relação ao import.meta.url https://github.com/vitejs/vite/issues/8427. Vou ver se consigo corrigir aqui e assim que conseguir te dou um toque 🙌🏻

**Comment by Kurumi30** [comment]
> Eai @Kurumi30 tudo bem? Estou dando uma lida aqui e isso parece ser um bug aberto do Vite em relação ao import.meta.url [vitejs/vite#8427](https://github.com/vitejs/vite/issues/8427). Vou ver se consigo corrigir aqui e assim que conseguir te dou um toque 🙌🏻

Certo mano, obrigado🤝

**Comment by bruno-sartori** [comment]
@Kurumi30 Fixed! 
![image](https://github.com/user-attachments/assets/bf86b781-ea7b-43af-9b19-d0b12b21e7cf)

**Comment by bruno-sartori** [comment]
Closing the issue
